### ISSUE TITLE
Deeper indents become code blocks.

### ISSUE THREAD

**Issue by nixnull** [AgoraNomic/ruleset-old#1]
For example: https://agoranomic.github.io/ruleset/#Rule1728

This also causes the inserted links to be in their plain format.

A quick fix is to make the regex not match if there's enough whitespace on the left-margin. A better fix is to find some way to avoid the code block formatting altogether.

Thoughts?

**Comment by Gaelan** [comment]
I plan on invoking [Cleanup Time](https://agoranomic.github.io/ruleset/#Rule2430) soon to convert all the rules into proper Markdown (while still making them readable in plain text, of course–I won't use any MD syntax which isn't plausible as normal plan text formatting).

**Comment by inquisitivecrystal** [comment]
@Gaelan: you'd did this, right?

**Comment by Gaelan** [comment]
Yep.
